name: deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: deploying everything to the staging machine

    steps:
      - name: ssh in the staging machine
      - run: |
          echo "hi there"
